# Generated by Django 4.2.5 on 2023-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
